export const ProjConstants = {
    ASSIST : 'Assist',
    MYBOT : 'My Bot',
    TRANSCRIPT : "Transcript",
    LIBRARY : 'Library',
    SETTINGS : 'Settings',
    SEARCH : 'Search',
    VOICE : 'voice',
    CHAT : 'chat',
    BOTID : 'botId',
    CONVESATIONID : 'conversationId',
    RUN : 'RUN',
    AGENTASSIST_RUN : 'Run with Agent Inputs',
    SEND : 'Send',
    COPY : 'Copy',
    COPIED : 'Copied',
    SHOW_MORE : 'Show more',
    SHOW_LESS : 'Show less',
    READ_MORE : 'Read more',
    READ_LESS : 'Read less',
    EXPAND : 'Expand',
    READ_MORE_EXPAND : 'Read more | Expand',
    CLOSE : 'Close',
    DIALOG : 'Dialog task',
    FAQ : 'FAQ',
    ARTICLE : 'Article',
    SNIPPET : 'Snippet',
    VIEW_ALL_FAQ : 'View All FAQs',
    VIEW_FEW_FAQ : 'View Few FAQs',
    VIEW_ALL_ARTICLES : 'View All Articles',
    VIEW_FEW_ARTICLES : 'View Few Articles',
    VIEW_ALL_SNIPPETS : 'View All Snippets',
    VIEW_FEW_SNIPPETS : 'View Few Snippets',
    AGENT_SEARCH : 'Agent Search',
    LIBRARY_SEARCH : 'Library Search',
    ENTER_DETAILS : 'EnterDetails',
    DISCARD_ALL : 'discard all',
    TERMINATE : 'Terminate',
    INTERRUPT : 'Interrupt',
    RESTORE : 'Restore',
    SUMMARY : 'Summary',
    INTENT : 'IntentName',
    HISTORY: 'History',
    PS_Y_REACH_START : 'ps-y-reach-start',
    PS_Y_REACH_END : 'ps-y-reach-end',
    PS_SCROLL_UP : 'ps-scroll-up',
    PROACTIVE_INITIAL_MODE : 'proactive_initial_mode',
    SMARTASSIST_SOURCE : 'smartassist-color-scheme',
    INCOMING : 'incoming',
    OUTGOING : 'outgoing',
    jToken : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjUzODYxNzgyMjMsImV4cCI6MTY2NTM4NjE3OTEyMywiYXVkIjoiIiwiaXNzIjoiY3MtZTRhMmI0YjYtM2RiZC01NWQwLWIwMjUtNDY2ZTVkMDRjOTgxIiwic3ViIjoiYy00NzJhNjYyLTQ5ZDYtNDM5Ny1hMjY1LTViNzE4ZDQ0MWNiNCIsImlzQW5vbnltb3VzIjpmYWxzZX0.1SN5BIEaQ4Rr6XpyKXR1AerNcIEmyDcnK6P0cpPkQzM"
}

export const storageConst = {
    CURRENT_TAB : 'currentTab',
    AGENT_ASSIST_STATE : 'agentAssistState',
    IS_WELCOMEMSG_PROCESSED : 'isWelcomeProcessed',
    INITIALTASK_GOING_ON : 'initialTaskGoingOn',
    AUTOMATION_GOING_ON_AFTER_REFRESH : 'automationGoingOnAfterRefresh',
    AUTOMATION_GOING_ON_AFTER_REFRESH_MYBOT : 'automationGoingOnAfterRefreshMyBot',
    FAQ_LIST : 'faqList',
    SEARCH_VALUE : 'search',
    PROACTIVE_MODE : 'proactiveMode',
    LANGUAGE : 'lang',
    THEME : 'theme',
    ENGLISH : 'en',
    AUTO : 'auto'
}

export const languages = {
    en: 'English',
    ar: 'Arabic',
    ja: 'Japanese',
    chi: 'Chinese',
    fr: 'French'
}